version: "3.9"

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: healthcheck
      POSTGRES_PASSWORD: securepass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres:
