version: "3.9"

services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: healthcheck
      POSTGRES_PASSWORD: healthcheck
      POSTGRES_DB: healthcheck
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
